spring.application.name=cardatabase

# H2 database
spring.datasource.url=jdbc:h2:mem:cardatabase
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 browser console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server configuration
server.port=8080
server.servlet.context-path=/api

# Actuator
management.endpoints.web.exposure.include=hea;th,info
management.info.env.enabled=true

# Actuator application information
info.app.name=Car Database API
info.app.descriptiob=REST API for managing cars
info.app.version=0.0.1
