spring.application.name=Super_Duper_Fun_Program
server.port = 7070

# Custom Application Properties
coach.name=Coach K
team.name=Blue Devils
fun.name=Bowling
fun.description=Rolling balls at pins
activity.name=Skydiving

# Spring Boot Actuator Management
management.endpoints.web.exposure.include=health, info, beans, mapping
Actuator endpoints [9, 10]

# JDBC Database Connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=
spring.datasource.password=

